<?php

namespace Egston\PimcoreHealthCheckBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('egston_pimcore_health_check');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
                ->booleanNode('enabled')
                    ->defaultTrue()
                    ->info('Globally enable or disable all health checks.')
                ->end()
                ->scalarNode('path')
                    ->defaultValue('/healthz')
                    ->info('URL path for the health check endpoint.')
                ->end()
                ->arrayNode('graphql')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultFalse()
                            ->info('Enable the configurable GraphQL health check.')
                        ->end()
                        ->arrayNode('endpoints')
                            ->arrayPrototype()
                                ->children()
                                    ->scalarNode('name')
                                        ->isRequired()
                                        ->cannotBeEmpty()
                                        ->info('Logical name of the endpoint (used in reporting).')
                                    ->end()
                                    ->scalarNode('url')
                                        ->isRequired()
                                        ->info('Absolute URL of the GraphQL endpoint.')
                                    ->end()
                                    ->scalarNode('query')
                                        ->defaultValue('{ __typename }')
                                        ->info('GraphQL query to execute.')
                                    ->end()
                                    ->floatNode('timeout')
                                        ->defaultValue(3.0)
                                        ->min(0.1)
                                        ->info('HTTP request timeout in seconds.')
                                    ->end()
                                    ->arrayNode('headers')
                                        ->normalizeKeys(false)
                                        ->scalarPrototype()->end()
                                        ->defaultValue([])
                                        ->info('Optional HTTP headers to include in the request.')
                                    ->end()
                                    ->scalarNode('api_key')
                                        ->defaultNull()
                                        ->info('Explicit API key appended as "apikey" query parameter when provided.')
                                    ->end()
                                    ->scalarNode('authorization_bearer')
                                        ->defaultNull()
                                        ->info('Convenience property to set a Bearer token in the Authorization header.')
                                    ->end()
                                    ->arrayNode('assert')
                                        ->addDefaultsIfNotSet()
                                        ->children()
                                            ->scalarNode('path')
                                                ->defaultNull()
                                                ->info('Dot-separated path to the value to validate (e.g. "data.health.status").')
                                            ->end()
                                            ->scalarNode('equals')
                                                ->defaultNull()
                                                ->info('Expected value for strict equality.')
                                            ->end()
                                            ->scalarNode('contains')
                                                ->defaultNull()
                                                ->info('Expected element within an array value.')
                                            ->end()
                                            ->booleanNode('is_empty')
                                                ->defaultNull()
                                                ->info('Expect the target value to be empty (true) or non-empty (false).')
                                            ->end()
                                        ->end()
                                        ->end()
                                    ->end()
                            ->end()
                            ->defaultValue([])
                            ->info('List of configured GraphQL endpoints.')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('graphql_internal')
                    ->addDefaultsIfNotSet()
                    ->info('In-process (Symfony sub-request) GraphQL checks. Avoids cluster-Service self-call deadlock at cold start; covers routing + controller + resolvers; does NOT exercise nginx/FastCGI.')
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultFalse()
                            ->info('Enable the in-process GraphQL health check.')
                        ->end()
                        ->arrayNode('endpoints')
                            ->arrayPrototype()
                                ->children()
                                    ->scalarNode('name')
                                        ->isRequired()
                                        ->cannotBeEmpty()
                                        ->info('Logical name (used in reporting as "graphql_internal_<name>").')
                                    ->end()
                                    ->scalarNode('path')
                                        ->isRequired()
                                        ->cannotBeEmpty()
                                        ->info('In-process URI path to dispatch (e.g. "/pimcore-graphql-webservices/public-content").')
                                    ->end()
                                    ->scalarNode('query')
                                        ->defaultValue('{ __typename }')
                                        ->info('GraphQL query to execute.')
                                    ->end()
                                    ->scalarNode('api_key')
                                        ->defaultNull()
                                        ->info('Optional API key appended as "apikey" query parameter when provided.')
                                    ->end()
                                    ->arrayNode('assert')
                                        ->addDefaultsIfNotSet()
                                        ->children()
                                            ->scalarNode('path')
                                                ->defaultNull()
                                                ->info('Dot-separated path to the value to validate.')
                                            ->end()
                                            ->scalarNode('equals')
                                                ->defaultNull()
                                                ->info('Expected value for strict equality.')
                                            ->end()
                                            ->scalarNode('contains')
                                                ->defaultNull()
                                                ->info('Expected element within an array value.')
                                            ->end()
                                            ->booleanNode('is_empty')
                                                ->defaultNull()
                                                ->info('Expect the target value to be empty (true) or non-empty (false).')
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                            ->defaultValue([])
                            ->info('List of in-process GraphQL endpoints to probe.')
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
